# Generated by Django 6.0.1 on 2026-01-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter (X)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('telegram', 'Telegram')], max_length=50, unique=True, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_emoji', models.CharField(default='🌐', max_length=10, verbose_name='Icon/Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
    ]
